apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: m7vg0e2g8-dotnet-basic
  janus-idp.io/tekton: m7vg0e2g8-dotnet-basic
  backstage.io/kubernetes-id: m7vg0e2g8-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: m7vg0e2g8-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
